### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [itsshaya/teacozy#5]
Grade: **Meets Expectations**

Overall, this project is working well. It has very clean HTML and is meeting the specification perfectly. A couple things I would work on is making sure you close your elements correctly, as well as including alt attributes on your images in order to provide our users with a text descriptor of the image. Next steps, I would look into learning about media queries in an effort to make your pages responsive so they will be viewable on all types of media such as phone, PC, laptop, etc: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries 

Good work!

**Comment by itsshaya** [comment]
Thank you, Conner!
